FROM node:20-alpine AS builder

RUN mkdir -p /app

WORKDIR /app

COPY . .

RUN yarn install

RUN yarn tsc

FROM node:20-alpine AS app

ENV NODE_ENV=production

RUN mkdir -p /app

WORKDIR /app

COPY --chown=node:node --from=builder /app/package.json /app
COPY --chown=node:node --from=builder /app/build/ /app

RUN yarn install --frozen-lockfile --production

EXPOSE 4500

ENTRYPOINT ["node", "index.js"]